### ISSUE TITLE
run the code

### ISSUE THREAD

**Issue by justinner** [Forrest0503/DIB_FCN#1]
你好，
    我觉得你的想法非常新颖，请问你的代码都是封装好的吗，可以告诉我怎么运行吗？

**Comment by Forrest0503** [comment]
代码是基于这个进行的封装https://github.com/ljanyst/image-segmentation-fcn ，先修改source_dibco.py，用来配置数据集，然后运行train.py进行训练，再运行binarize.py进行二值化

**Comment by justinner** [comment]
非常感谢你的分享，再次感谢。我在运行train.py的时候出现了错误，一直找不到原因，你能帮我看一下吗？
Traceback (most recent call last):
  File "/home/jia/下载/DIB_FCN-master/train.py", line 57, in <module>
    os.makedirs(args.name)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: 'test'

**Comment by Forrest0503** [comment]
这是因为当前目录下已经存在一个叫'test'的模型了，而模型默认的名字就叫'test'，所以你要么删掉旧的test文件夹，要么加上--name参数来指定模型的名字 ，像这样python3 train.py --name=其他的名字

**Comment by justinner** [comment]
謝謝你，原來是這樣，可以在CPU上跑嗎

**Comment by justinner** [comment]
你好同學，我在運行train.py打時候出現鏈接問題，可以請教一下嗎？
Traceback (most recent call last):
  File "/home/jia/下载/DIB_FCN-master/train.py", line 94, in <module>
    net.build_from_vgg(args.vgg_dir, source.num_classes, progress_hook='tqdm')
  File "/home/jia/下载/DIB_FCN-master/fcnvgg.py", line 66, in build_from_vgg
    self.__download_vgg(vgg_dir, progress_hook)
  File "/home/jia/下载/DIB_FCN-master/fcnvgg.py", line 120, in __download_vgg
    urlretrieve(url, vgg_archive, pbar.hook)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 110] **Connection timed out**

Process finished with exit code 1
